# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65697c3cbad5e574daa1983c8b624f93ae0ee683b62c592ce88a95112fab77bbb45a2d8a1cb47fd1b9aed79ef1b8ec79d7f9c598c982d80091acfe546b38c5e

test:
  secret_key_base: 5d39b42fc939d172f3f4db64fc9f2ef443d597e0dcf62c0d1d66ff58310f5edc1578ef334381ed6f156ba7ebf09768676509e3c20a22d395126625b29acd6f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
